apiVersion : apps/v1
kind: Deployment
metadata:
  name: "trouble1cluster-0d78"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "trouble1cluster-0d78"
  template:
    metadata:
      labels:
        app: "trouble1cluster-0d78"
    spec:
      containers:
        - name: "trouble1cluster-0d78"
          image: "trouble1container.azurecr.io/trouble1cluster"
          ports:
          - containerPort: 80