apiVersion: v1
kind: Service
metadata:
    name: "trouble1cluster-0d78"
    labels:
        app: "trouble1cluster-0d78"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "trouble1cluster-0d78"